/*************************************************************************
                           FullHistory  -  description
                             -------------------
    dï¿½but                : ${date}
    copyright            : (C) ${year} par ${user}
*************************************************************************/

//---------- Interface de la classe <FullHistory> (fichier ${file_name}) ------
#if ! defined ( FULLHISTORY_H )
#define FULLHISTORY_H

//--------------------------------------------------- Interfaces utilisï¿½es
#include "Shape.h"
#include "History.h"
#include <map>
#include <string>
//------------------------------------------------------------- Constantes

//------------------------------------------------------------------ Types

//------------------------------------------------------------------------
// Rï¿½le de la classe <FullHistory>
//
//
//------------------------------------------------------------------------

class FullHistory : public History
{
//----------------------------------------------------------------- PUBLIC

public:
//----------------------------------------------------- Mï¿½thodes publiques
    // type Mï¿½thode ( liste de paramï¿½tres );
    // Mode d'emploi :
    //
    // Contrat :
    //
    virtual History* Cancel(std::map<std::string, Shape*> & model);//cancel the action done in this history entry
    //Returns the history entry generated by the canceling (goes from undo to redo or from redo to undo)
    virtual void Clean();//Definitely deletes the target

//------------------------------------------------- Surcharge d'opï¿½rateurs
    FullHistory & operator = ( const FullHistory & unFullHistory );
    // Mode d'emploi :
    //
    // Contrat :
    //


//-------------------------------------------- Constructeurs - destructeur
    FullHistory ( const FullHistory & unFullHistory );
    // Mode d'emploi (constructeur de copie) :
    //
    // Contrat :
    //

    FullHistory ( std::string type, std::map<std::string, Shape*> & model );
    // Mode d'emploi :
    //
    // Contrat :
    //

    virtual ~FullHistory ( );
    // Mode d'emploi :
    //
    // Contrat :
    //

//------------------------------------------------------------------ PRIVE

protected:
//----------------------------------------------------- Mï¿½thodes protï¿½gï¿½es

private:
//------------------------------------------------------- Mï¿½thodes privï¿½es

protected:
//----------------------------------------------------- Attributs protégés
map<string, Shape*> prevModel;


private:
//------------------------------------------------------- Attributs privï¿½s

//---------------------------------------------------------- Classes amies

//-------------------------------------------------------- Classes privï¿½es

//----------------------------------------------------------- Types privï¿½s

};

//----------------------------------------- Types dï¿½pendants de <FullHistory>

#endif // FULLHISTORY_H
