/*************************************************************************
                           FullHistory  -  description
                             -------------------
    début                : ${date}
    copyright            : (C) ${year} par ${user}
*************************************************************************/

//---------- Interface de la classe <FullHistory> (fichier ${file_name}) ------
#if ! defined ( FULLHISTORY_H )
#define FULLHISTORY_H

//--------------------------------------------------- Interfaces utilisées
#include "Shape.h"
#include "History.h"
#include <map>
#include <string>
//------------------------------------------------------------- Constantes

//------------------------------------------------------------------ Types

//------------------------------------------------------------------------
// Rôle de la classe <FullHistory>
//
//
//------------------------------------------------------------------------

class FullHistory : public History
{
//----------------------------------------------------------------- PUBLIC

public:
//----------------------------------------------------- Méthodes publiques
    // type Méthode ( liste de paramètres );
    // Mode d'emploi :
    //
    // Contrat :
    //
    virtual History* Cancel(map<string, Shape*> & model);//cancel the action done in this history entry
    //Returns the history entry generated by the canceling (goes from undo to redo or from redo to undo)
    virtual void Clean();//Definitely deletes the target

//------------------------------------------------- Surcharge d'opérateurs
    FullHistory & operator = ( const FullHistory & unFullHistory );
    // Mode d'emploi :
    //
    // Contrat :
    //


//-------------------------------------------- Constructeurs - destructeur
    FullHistory ( const FullHistory & unFullHistory );
    // Mode d'emploi (constructeur de copie) :
    //
    // Contrat :
    //

    FullHistory ( string type, map<string, Shape*> & model );
    // Mode d'emploi :
    //
    // Contrat :
    //

    virtual ~FullHistory ( );
    // Mode d'emploi :
    //
    // Contrat :
    //

//------------------------------------------------------------------ PRIVE

protected:
//----------------------------------------------------- Méthodes protégées

private:
//------------------------------------------------------- Méthodes privées

protected:
//----------------------------------------------------- Attributs protégés

map<string, Shape*> prevModel;


private:
//------------------------------------------------------- Attributs privés

//---------------------------------------------------------- Classes amies

//-------------------------------------------------------- Classes privées

//----------------------------------------------------------- Types privés

};

//----------------------------------------- Types dépendants de <FullHistory>

#endif // FULLHISTORY_H
