/*************************************************************************
                           History  -  description
                             -------------------
    début                : ${date}
    copyright            : (C) ${year} par ${user}
*************************************************************************/

//---------- Interface de la classe <History> (fichier ${file_name}) ------
#if ! defined ( HISTORY_H )
#define HISTORY_H

//--------------------------------------------------- Interfaces utilisées
#include "Shape.h"
#include <map>
//------------------------------------------------------------- Constantes

//------------------------------------------------------------------ Types

//------------------------------------------------------------------------
// Rôle de la classe <History>
//
//
//------------------------------------------------------------------------

class History
{
//----------------------------------------------------------------- PUBLIC

public:
//----------------------------------------------------- Méthodes publiques
    // type Méthode ( liste de paramètres );
    // Mode d'emploi :
    //
    // Contrat :
    //
    virtual History* Cancel(map<string, Shape*> & model)=0;//Cancels the action
    //Returns the history entry generated by the canceling (goes from undo to redo or from redo to undo)
    virtual void Clean()=0;//Definitely deletes the target

//------------------------------------------------- Surcharge d'opérateurs
    History & operator = ( const History & unHistory );
    // Mode d'emploi :
    //
    // Contrat :
    //


//-------------------------------------------- Constructeurs - destructeur
    History ( const History & unHistory );
    // Mode d'emploi (constructeur de copie) :
    //
    // Contrat :
    //

    History ( );
    // Mode d'emploi :
    //
    // Contrat :
    //

    virtual ~History ( );
    // Mode d'emploi :
    //
    // Contrat :
    //

//------------------------------------------------------------------ PRIVE

protected:
//----------------------------------------------------- Méthodes protégées

private:
//------------------------------------------------------- Méthodes privées

protected:
//----------------------------------------------------- Attributs protégés

private:
//------------------------------------------------------- Attributs privés

//---------------------------------------------------------- Classes amies

//-------------------------------------------------------- Classes privées

//----------------------------------------------------------- Types privés

};

//----------------------------------------- Types dépendants de <History>

#endif // HISTORY_H
