/*************************************************************************
                           SingleHistory  -  description
                             -------------------
    début                : ${date}
    copyright            : (C) ${year} par ${user}
*************************************************************************/

//---------- Interface de la classe <SingleHistory> (fichier ${file_name}) ------
#if ! defined ( SINGLEHISTORY_H )
#define SINGLEHISTORY_H

//--------------------------------------------------- Interfaces utilisées
#include "Shape.h"
#include "History.h"
#include <map>
//------------------------------------------------------------- Constantes

//------------------------------------------------------------------ Types

//------------------------------------------------------------------------
// Rôle de la classe <SingleHistory>
//
//
//------------------------------------------------------------------------

class SingleHistory : public History
{
//----------------------------------------------------------------- PUBLIC

public:
//----------------------------------------------------- Méthodes publiques
    // type Méthode ( liste de paramètres );
    // Mode d'emploi :
    //
    // Contrat :
    //
    virtual History* Cancel(std::map<std::string, Shape*> & model);
    //Cancel the action done in this history entry
    //Returns the history entry generated by the canceling (goes from undo to redo or from redo to undo)

//------------------------------------------------- Surcharge d'opérateurs
    SingleHistory & operator = ( const SingleHistory & unSingleHistory );
    // Mode d'emploi :
    //
    // Contrat :
    //


//-------------------------------------------- Constructeurs - destructeur
    SingleHistory ( const SingleHistory & unSingleHistory );
    // Mode d'emploi (constructeur de copie) :
    //
    // Contrat :
    //

    SingleHistory ( std::string type, Shape* atarget );
    // Mode d'emploi :
    //
    // Contrat :
    //

    virtual ~SingleHistory ( );
    // Mode d'emploi :
    //
    // Contrat :
    //

//------------------------------------------------------------------ PRIVE

protected:
//----------------------------------------------------- Méthodes protégées

private:
//------------------------------------------------------- Méthodes privées

protected:
//----------------------------------------------------- Attributs protégés
Shape* target;


private:
//------------------------------------------------------- Attributs privés

//---------------------------------------------------------- Classes amies

//-------------------------------------------------------- Classes privées

//----------------------------------------------------------- Types privés

};

//----------------------------------------- Types dépendants de <SingleHistory>

#endif // SINGLEHISTORY_H
